# The URL the site will be built for
base_url = "https://princesssarmica.github.io/"

# Website Title
title = "Medijska predilnica"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme used
theme = "DeepThought"

# News posts categories and tags
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# Enable external libraries

katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Domov" },
  { url = "$BASE_URL/seminarji", name = "Seminarji" },
  { url = "$BASE_URL/novice", name = "Novice" },
  { url = "$BASE_URL/radio", name = "Radio" },
  { url = "$BASE_URL/tags", name = "Etikete" },
  { url = "$BASE_URL/categories", name = "Kategorije" },
 ]},
]

locale = "sl_SI"

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/web-app-manifest-192x192.png"
favicon_32x32 = "/icons/web-app-manifest-512x512.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/favicon.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "princessSarmica"
avatar = "/images/avatar.svg"

# Social links
[extra.social]
email = "medijske@um.si"
facebook = "medijskekomunikacijeFERI"
youtube = "@medijskekomunikacijeferi3538"
github = "princessSarmica"
twitter = "@medijske"
instagram = "medijske.um.si"

# To add google analytics
[extra.analytics]
google = "<your_gtag>"

# To add disqus comments
[extra.commenting]
disqus = "<your_disqus_shortname>"

# To enable mapbox maps
[extra.mapbox]
enabled = true
access_token = "<your_access_token>"